#if !canImport(ObjectiveC)
import XCTest

extension ExecutionContextTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ExecutionContextTests = [
        ("testTaskRunOnBackground", testTaskRunOnBackground),
        ("testTaskRunOnMain", testTaskRunOnMain),
        ("testTaskRunWithAtomic", testTaskRunWithAtomic),
        ("testTaskRunWithDelay", testTaskRunWithDelay),
        ("testTaskWithVoidInput", testTaskWithVoidInput),
    ]
}

extension FutureBasicTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FutureBasicTests = [
        ("testAsyncResolvingWithDelayFuture", testAsyncResolvingWithDelayFuture),
        ("testFutureWithInitialValue", testFutureWithInitialValue),
        ("testMultithradResolvingFuture", testMultithradResolvingFuture),
        ("testResolvingFuture", testResolvingFuture),
        ("testResolvingMultipleTimesInTheMiddleOfAddingCompletion1", testResolvingMultipleTimesInTheMiddleOfAddingCompletion1),
        ("testResolvingMultipleTimesInTheMiddleOfAddingCompletion2", testResolvingMultipleTimesInTheMiddleOfAddingCompletion2),
        ("testResolvingOnceInTheMiddleWhenConcurrentlyAddingCompletionFuture", testResolvingOnceInTheMiddleWhenConcurrentlyAddingCompletionFuture),
        ("testResolvingOnceWhenConcurrentlyAddingCompletionFuture", testResolvingOnceWhenConcurrentlyAddingCompletionFuture),
        ("testResolvingOnceWithManyCompletionFuture", testResolvingOnceWithManyCompletionFuture),
        ("testResolvingTwiceOneInTheMiddleOfAddingCompletion_AndOneInCompletingOfAddingCompletion", testResolvingTwiceOneInTheMiddleOfAddingCompletion_AndOneInCompletingOfAddingCompletion),
        ("testSimpleFuture", testSimpleFuture),
    ]
}

extension FutureInitResolverTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FutureInitResolverTests = [
        ("testInitWithResolver", testInitWithResolver),
        ("testInitWithResolver_ResolveMultipleTimes", testInitWithResolver_ResolveMultipleTimes),
        ("testInitWithResolver_ResolveMultipleTimesWithDelay", testInitWithResolver_ResolveMultipleTimesWithDelay),
        ("testInitWithResolver_ResolveWithDelay", testInitWithResolver_ResolveWithDelay),
        ("testInitWithResolver_ResolveWithDelay_nilReferenceBeforeSubscribing", testInitWithResolver_ResolveWithDelay_nilReferenceBeforeSubscribing),
        ("testInitWithResolver_ResolveWithNODelay_nilReferenceBeforeSubscribing", testInitWithResolver_ResolveWithNODelay_nilReferenceBeforeSubscribing),
        ("testInitWithResolver_WithoutResolving", testInitWithResolver_WithoutResolving),
    ]
}

extension FutureMappingTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FutureMappingTest = [
        ("testFutureFlatMap", testFutureFlatMap),
        ("testFutureMapWithInitialValue", testFutureMapWithInitialValue),
        ("testFutureMapWithoutInitialValue", testFutureMapWithoutInitialValue),
        ("testFutureMapWithoutResolvingValue", testFutureMapWithoutResolvingValue),
    ]
}

extension FutureOperatorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FutureOperatorTests = [
        ("testFlatMapOperator", testFlatMapOperator),
        ("testMapOperator", testMapOperator),
        ("testMapOperatorToDifferentType", testMapOperatorToDifferentType),
        ("testMapOperatorWithDelayResolving", testMapOperatorWithDelayResolving),
    ]
}

extension FutureSubscriptionContextTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FutureSubscriptionContextTests = [
        ("testSubscribeOnBackgroundContext", testSubscribeOnBackgroundContext),
        ("testSubscribeOnCurrentContext", testSubscribeOnCurrentContext),
        ("testSubscribeOnMainContext", testSubscribeOnMainContext),
        ("testSubscribeOnMainContextEvenFutureBeingResolvedBeforeSubscription", testSubscribeOnMainContextEvenFutureBeingResolvedBeforeSubscription),
        ("testSubscribeOnMainContextEvenFutureBeingResolvedBeforeSubscription2", testSubscribeOnMainContextEvenFutureBeingResolvedBeforeSubscription2),
        ("testSubscribeOnMainContextWithChaining", testSubscribeOnMainContextWithChaining),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ExecutionContextTests.__allTests__ExecutionContextTests),
        testCase(FutureBasicTests.__allTests__FutureBasicTests),
        testCase(FutureInitResolverTests.__allTests__FutureInitResolverTests),
        testCase(FutureMappingTest.__allTests__FutureMappingTest),
        testCase(FutureOperatorTests.__allTests__FutureOperatorTests),
        testCase(FutureSubscriptionContextTests.__allTests__FutureSubscriptionContextTests),
    ]
}
#endif
