#if !canImport(ObjectiveC)
import XCTest

extension ExecutionContextTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ExecutionContextTests = [
        ("testTaskRunOnBackground", testTaskRunOnBackground),
        ("testTaskRunOnMain", testTaskRunOnMain),
        ("testTaskRunWithAtomic", testTaskRunWithAtomic),
        ("testTaskRunWithDelay", testTaskRunWithDelay),
        ("testTaskWithVoidInput", testTaskWithVoidInput),
    ]
}

extension FutureBasicTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FutureBasicTests = [
        ("testAsyncResolvingWithDelayFuture", testAsyncResolvingWithDelayFuture),
        ("testFutureWithInitialValue", testFutureWithInitialValue),
        ("testMultithradResolvingFuture", testMultithradResolvingFuture),
        ("testResolvingFuture", testResolvingFuture),
        ("testResolvingMultipleTimesInTheMiddleOfAddingCompletion1", testResolvingMultipleTimesInTheMiddleOfAddingCompletion1),
        ("testResolvingMultipleTimesInTheMiddleOfAddingCompletion2", testResolvingMultipleTimesInTheMiddleOfAddingCompletion2),
        ("testResolvingOnceInTheMiddleWhenConcurrentlyAddingCompletionFuture", testResolvingOnceInTheMiddleWhenConcurrentlyAddingCompletionFuture),
        ("testResolvingOnceWhenConcurrentlyAddingCompletionFuture", testResolvingOnceWhenConcurrentlyAddingCompletionFuture),
        ("testResolvingOnceWithManyCompletionFuture", testResolvingOnceWithManyCompletionFuture),
        ("testResolvingTwiceOneInTheMiddleOfAddingCompletion_AndOneInCompletingOfAddingCompletion", testResolvingTwiceOneInTheMiddleOfAddingCompletion_AndOneInCompletingOfAddingCompletion),
        ("testSimpleFuture", testSimpleFuture),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ExecutionContextTests.__allTests__ExecutionContextTests),
        testCase(FutureBasicTests.__allTests__FutureBasicTests),
    ]
}
#endif
